### ISSUE TITLE
Some various bugs, suggestions, and questions

### ISSUE THREAD

**Issue by eMorph** [TurtleMan64/Sonic3DGamev3#24]
Bug 1: I can't seem to get the game to work with a framerate cap under Wine, so I have to constantly unplug my laptop to keep the framerate decent.
Bug 2: After a certain amount of time, the game can crash for no discernible reason.
Bug 3: At high speeds, characters can clip through gaps in the stage geometry smaller than the character hitbox.

Suggestion 1: Variable framerate based on the system timer and monitor refresh rate rather than a fixed rate and in-engine timer.
Suggestion 2: Linux support. All it would take is removing the dependency on various Windows-only services, since it's already an OpenGL game.
Sugggestion 3: Characters should have larger hitboxes/models to match the levels' expected character size.
Suggestion 4: Could you release the level file format? I think that would be really cool, and the modding possibilities would be awesome!

Question 1: What do the NPCs do? As far as I can tell, the amount you've gotten just shows up in the Extras menu. I've heard that they can unlock new cfharacters, but I have yet to see this in action.

**Comment by eMorph** [comment]
Oh, also another suggestion: camera pitch should be related to player pitch, so that you can always see the character.

**Comment by TurtleMan64** [comment]
Sorry for late reply, I don't usually get these so I don't check very often.

For Linux support, that should be already taken care of. All of the Windows only stuff should be behind `#ifdef _WIN32` checks. I remember one of my friends got it to compile on his Linux machine just fine. Is there a specific error that's happening?

For unlocking characters, there are 4 in total:
* Beat Arcade mode
* Get all A ranks
* Find at least 50% of the NPCs
* Find all the NPCs

For the other suggestions, most of them have been done in the new project [SAB2](https://github.com/TurtleMan64/SAB2), which is a sequel to this game. It's not done yet but you can build and run it since it's also open source. For example, the framerate can be variable (suggestion 1). The camera also always follows behind the player, even when going around steep slopes and loops (the additional suggestion). I don't really plan on adding this to SAB because it would require a pretty big overhaul (and is pretty much what SAB2 is already).

**Comment by eMorph** [comment]
Oh, cool, thanks. I was worried about compiling for Linux because it looked like a large amount of features were dependent on the Windows APIs (Wine can emulate those but only for exe files). If Linux GL works natively with this, then that's great!

The other thing I was really wondering is how to switch characters once they are unlocked. And I'll definitely try out SAB2!

**Comment by TurtleMan64** [comment]
You switch characters in the Extras menu on the main menu. At the bottom it will say "Play as" and then you go left/right to change characters. I think if you don't have any unlocked then it will just stay as Sonic.
